### ISSUE TITLE
Funktioniert nicht richtig

### ISSUE THREAD

**Issue by Lauchmelder23** [epioos/big-int#1]
Commit e1a1983 hat die Library für mich kaputt gemacht

**Comment by epioos** [comment]
bitte warten Sie geduldig auf die finale Version, ich arbeite mich Hochdruck und unter dem Einfluss von viel RedBull an der Fertigstellung des Projekts. GaliGrü dein Eventmanager

**Comment by Lauchmelder23** [comment]
ja hm ja puh
